package common.GUI;

/**
 *
 * @author DHT-Chord Team
 */
public class DirChoserDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog.
     *
     * @param parent
     * @param modal
     */
    public DirChoserDialog(MainWindow parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setDefaultLookAndFeelDecorated(true);
        this.jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser1.setBackground(new java.awt.Color(1, 1, 1));
        jFileChooser1.setDialogTitle("");
        jFileChooser1.setFont(new java.awt.Font("Bitstream Charter", 1, 13)); // NOI18N
        jFileChooser1.setForeground(new java.awt.Color(254, 254, 254));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("ApproveSelection")) {
            this.setVisible(false);
            if (parent == null) {
                return;
            }
            parent.getFileApp().changeDirectrory(this.jFileChooser1.getSelectedFile());
            parent.getDirText().setText(this.jFileChooser1.getSelectedFile().toString());

        }
        if (evt.getActionCommand().equals("CancelSelection")) {
            this.setVisible(false);
        }
        this.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    public java.io.File getFile() {
        return jFileChooser1.getSelectedFile();
    }
    MainWindow parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
