package common.GUI;

import FileApplication.MaybeAnApp;
import KeyManager.Mapper;
import chord.Node;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * GUI class.
 * @author DHT-Chord Team.
 */
public class MainWindow extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form NewJFrame.
     */
    public MainWindow() {

        this.img = new ImageIcon("src/common/GUI/Pirate.png");
        // this.img2= new ImageIcon("src/common/GUI/Bitlord.png");
        initComponents();
        updater = new Thread(this);
        updater.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        userText = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        fileNameDucc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ChoseDirectoryButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ServerText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClientText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DirText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DHTText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        KeysInfoText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        KeyActivityText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ChordVarsText = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        FingerTableText = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ChordActivityText = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setForeground(java.awt.Color.green);
        setIconImage(img.getImage());

        jTabbedPane1.setBackground(new java.awt.Color(236, 229, 206));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setForeground(new java.awt.Color(28, 20, 13));
        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(236, 229, 206));
        jPanel4.setForeground(new java.awt.Color(254, 254, 254));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel10.setBackground(java.awt.SystemColor.text);
        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(28, 20, 13));
        jLabel10.setText("Search for Filename");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Bitstream Charter", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(28, 20, 13));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(203, 232, 107));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(28, 20, 13));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/common/GUI/Nyan_Cat.gif"))); // NOI18N
        jButton1.setText("Search");
        jButton1.setAlignmentY(0.0F);
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        userText.setBackground(new java.awt.Color(28, 20, 13));
        userText.setColumns(1);
        userText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        userText.setForeground(new java.awt.Color(203, 232, 107));
        userText.setRows(5);
        userText.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane9.setViewportView(userText);

        jButton3.setBackground(new java.awt.Color(203, 232, 107));
        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(28, 20, 13));
        jButton3.setText("Find Successor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fileNameDucc.setEditable(false);
        fileNameDucc.setBackground(new java.awt.Color(255, 255, 255));
        fileNameDucc.setFont(new java.awt.Font("Bitstream Charter", 0, 13)); // NOI18N
        fileNameDucc.setForeground(new java.awt.Color(28, 20, 13));

        jLabel11.setBackground(new java.awt.Color(254, 254, 254));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(28, 20, 13));
        jLabel11.setText("----General Activity-----");

        jButton4.setBackground(new java.awt.Color(203, 232, 107));
        jButton4.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(28, 20, 13));
        jButton4.setText("EXIT Node");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane10.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileNameDucc))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(fileNameDucc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jButton1)
                                .addGap(90, 90, 90)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jButton4)))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("User Level", jPanel4);

        jPanel1.setBackground(new java.awt.Color(236, 229, 206));
        jPanel1.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.setFont(new java.awt.Font("Bitstream Charter", 0, 14)); // NOI18N

        ChoseDirectoryButton.setBackground(new java.awt.Color(203, 232, 107));
        ChoseDirectoryButton.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ChoseDirectoryButton.setForeground(new java.awt.Color(28, 20, 13));
        ChoseDirectoryButton.setText("Change");
        ChoseDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoseDirectoryButtonActionPerformed(evt);
            }
        });
        ChoseDirectoryButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ChoseDirectoryButtonKeyReleased(evt);
            }
        });

        ServerText.setEditable(false);
        ServerText.setBackground(new java.awt.Color(28, 20, 13));
        ServerText.setColumns(20);
        ServerText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        ServerText.setForeground(new java.awt.Color(203, 232, 107));
        ServerText.setRows(5);
        jScrollPane2.setViewportView(ServerText);

        ClientText.setEditable(false);
        ClientText.setBackground(new java.awt.Color(28, 20, 13));
        ClientText.setColumns(20);
        ClientText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        ClientText.setForeground(new java.awt.Color(203, 232, 107));
        ClientText.setRows(5);
        jScrollPane3.setViewportView(ClientText);

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 20, 13));
        jLabel1.setText("---Client Notifications---");

        jLabel2.setBackground(new java.awt.Color(1, 1, 1));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 20, 13));
        jLabel2.setText("---Server Notifications---");

        jLabel3.setBackground(new java.awt.Color(28, 20, 13));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 20, 13));
        jLabel3.setText("Directory:");

        DirText.setEditable(false);
        DirText.setBackground(new java.awt.Color(255, 255, 255));
        DirText.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DirText.setForeground(new java.awt.Color(28, 20, 13));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/common/GUI/kth_logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DirText, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ChoseDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChoseDirectoryButton))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("File,TCP Level", jPanel1);

        jPanel2.setBackground(new java.awt.Color(236, 229, 206));

        DHTText.setEditable(false);
        DHTText.setBackground(new java.awt.Color(28, 20, 13));
        DHTText.setColumns(20);
        DHTText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        DHTText.setForeground(new java.awt.Color(203, 232, 107));
        DHTText.setRows(5);
        jScrollPane1.setViewportView(DHTText);

        KeysInfoText.setEditable(false);
        KeysInfoText.setBackground(new java.awt.Color(28, 20, 13));
        KeysInfoText.setColumns(20);
        KeysInfoText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        KeysInfoText.setForeground(new java.awt.Color(203, 232, 107));
        KeysInfoText.setRows(5);
        jScrollPane4.setViewportView(KeysInfoText);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 20, 13));
        jLabel4.setText("---Keys Info---");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 20, 13));
        jLabel5.setText("---DHT kept by Node---");

        KeyActivityText.setEditable(false);
        KeyActivityText.setBackground(new java.awt.Color(28, 20, 13));
        KeyActivityText.setColumns(20);
        KeyActivityText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        KeyActivityText.setForeground(new java.awt.Color(203, 232, 107));
        KeyActivityText.setRows(5);
        jScrollPane5.setViewportView(KeyActivityText);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(28, 20, 13));
        jLabel6.setText("---Activity---");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Key Level", jPanel2);

        jPanel3.setBackground(new java.awt.Color(236, 229, 206));
        jPanel3.setForeground(new java.awt.Color(255, 27, 0));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(28, 20, 13));
        jLabel7.setText("---Main Variables---");

        ChordVarsText.setEditable(false);
        ChordVarsText.setBackground(new java.awt.Color(28, 20, 13));
        ChordVarsText.setColumns(20);
        ChordVarsText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        ChordVarsText.setForeground(new java.awt.Color(203, 232, 107));
        ChordVarsText.setRows(5);
        ChordVarsText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(ChordVarsText);

        FingerTableText.setEditable(false);
        FingerTableText.setBackground(new java.awt.Color(28, 20, 13));
        FingerTableText.setColumns(20);
        FingerTableText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        FingerTableText.setForeground(new java.awt.Color(203, 232, 107));
        FingerTableText.setLineWrap(true);
        FingerTableText.setRows(5);
        FingerTableText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(FingerTableText);

        jLabel8.setBackground(new java.awt.Color(1, 1, 1));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(28, 20, 13));
        jLabel8.setText("---Finger Table---");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(28, 20, 13));
        jLabel9.setText("---Chord Activity---");

        ChordActivityText.setEditable(false);
        ChordActivityText.setBackground(new java.awt.Color(28, 20, 13));
        ChordActivityText.setColumns(20);
        ChordActivityText.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        ChordActivityText.setForeground(new java.awt.Color(203, 232, 107));
        ChordActivityText.setRows(5);
        ChordActivityText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ChordActivityText.setSelectionColor(new java.awt.Color(145, 153, 92));
        jScrollPane8.setViewportView(ChordActivityText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chord Level", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Lookup requested file and download it if it exists.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String fname = jTextField1.getText();
        if (jTextField1.getText().isEmpty()) {
            return;
        }
        int hash = common.Hasher.myCode(fname);
        userText.append(">Hash of requested file:"+hash+"\n");
        if (fileApp.mapCode(hash) != null) {
            userText.append(">You already have this File!\n");
            return;
        }
        fileApp.download(new java.io.File(DirText.getText() + java.io.File.separator + jTextField1.getText()), hash);

    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Find successor of given file name.
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            long start = System.currentTimeMillis();
            String fname = jTextField1.getText();
            if (jTextField1.getText().isEmpty()) {
                return;
            }
            int hash = common.Hasher.myCode(fname);
            userText.append(">Hash of filename:"+hash+"\n");
            int s = chord.FindSuccessor(hash).getNodeKey();
            String sr = "" + s;
            fileNameDucc.setText(sr);
            long end1 = System.currentTimeMillis() - start;
            float end = (float)((System.currentTimeMillis() - start)/1000);
            userText.append(">FindSuccessor took "+end1+" milliseconds\n");
        } catch (RemoteException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Leave chord ring and exit gui.
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chord.leave();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ChoseDirectoryButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChoseDirectoryButtonKeyReleased

    }//GEN-LAST:event_ChoseDirectoryButtonKeyReleased

    private void ChoseDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoseDirectoryButtonActionPerformed
        // TODO add your handling code here:
        DirChoserDialog fc = new DirChoserDialog(this, true);
        fc.setVisible(true);
    }//GEN-LAST:event_ChoseDirectoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public JTextArea getClientText() {
        return this.ClientText;
    }

    /**
     * 
     * @param chord 
     */
    public void setChord(Node chord) {
        this.chord = chord;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getServerText() {
        return this.ServerText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getChordVarsText() {
        return ChordVarsText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getDHTText() {
        return DHTText;
    }

    /**
     * 
     * @return 
     */
    public JTextField getDirText() {
        return DirText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getFingerTableText() {
        return FingerTableText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getKeyActivityText() {
        return KeyActivityText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getKeysInfoText() {
        return KeysInfoText;
    }

    /**
     * 
     * @return 
     */
    public JTextArea getChordActivityText() {
        return ChordActivityText;
    }

    /**
     * 
     * @param fileApp 
     */
    public void setFileApp(MaybeAnApp fileApp) {
        this.fileApp = fileApp;
    }

    /**
     * 
     * @return 
     */
    public MaybeAnApp getFileApp() {
        return fileApp;
    }

    /**
     * 
     * @param m 
     */
    public void setMapper(Mapper m) {
        mapper = m;
    }

    /**
     * Print variables to GUI log.
     */
    public void run() {
        this.setVisible(true);
        while (!Thread.currentThread().isInterrupted()) {
            try {
                if (this.chord != null) {
                    chord.printVars();
                    this.chord.printFingers();
                }
                if (this.mapper != null) {
                    mapper.printInfo();
                    mapper.printMap();
                } else {
                    this.getKeysInfoText().setText("==no Mapper connected===");
                }
                Thread.sleep(500);
            } catch (Exception ex) {
            }
            this.repaint();
        }//while(true)

    }//run()

        
    private chord.Node chord;
    private FileApplication.MaybeAnApp fileApp;
    private Mapper mapper;
    ImageIcon img;
    ImageIcon img2;
    Thread updater;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ChordActivityText;
    private javax.swing.JTextArea ChordVarsText;
    private javax.swing.JButton ChoseDirectoryButton;
    private javax.swing.JTextArea ClientText;
    private javax.swing.JTextArea DHTText;
    private javax.swing.JTextField DirText;
    private javax.swing.JTextArea FingerTableText;
    private javax.swing.JTextArea KeyActivityText;
    private javax.swing.JTextArea KeysInfoText;
    private javax.swing.JTextArea ServerText;
    private javax.swing.JTextField fileNameDucc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea userText;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     *
     * @param jTextArea1
     */
    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }
    // End of variables declaration

    /**
     *
     * @return
     */
    public synchronized JTextArea getUserText() {
        return userText;
    }
}
